#' Visualize MSI regions on optical image
#'
#' This function simply does visualization of MSI regions on the supplied optical image. 
#'
#' @param imgPath: 	The path to the optical image. 
#' @param regions: the regions object as generated by `msiTools::GetRegions`. 
#' @param saveImg: whether to save the result in the same directory. defaults to `FALSE`. 
#' @return
#' Plots the overlay of MSI on the optical image and returns the original img as `ÈBImage` object. 
#'
#' @export
#'
visualizeRegions     = function(imgPath, regions, saveImg = FALSE) {
       
       
       
       # load the optical image
       img           = EBImage::readImage(files = imgPath)
       
       # transform the regions' polygons to opticla coordinates
       opticalPoly   = lapply(regions$polyPoints, FUN = regions$meta$msiToOpticalTransFun)
       
       # transform the coordinates of the detected matrix pixels into optical coordinates
       opticalPoints = regions$meta$msiToOpticalTransFun(as.data.frame(do.call("rbind", regions$allPoints)))
       
       
       
       
       EBImage::display(img, method = "raster")
       title("MSI on optical image.png", cex.main = 1)
       points(opticalPoints, pch = 20, col = rgb(1,0,0, 0.05), cex = 0.1)
       for(iii in 1 : length(opticalPoly))
       {
              lines(opticalPoly[[iii]], col = "black", lty = "dashed", cex = 2)
       }
       
       

       if(saveImg)
       {
              # plot the the detecetd martix-pixels ontop of the optical image
              Cairo::Cairo(file = file.path(dirname(imgPath), paste0("MSI on optical image.png")),
                     width = 3000, height = 2000, type = "png", units = "px",
                     dpi = "auto")

              EBImage::display(img, method = "raster")
              title("MSI on optical image", cex.main = 1)
              points(opticalPoints, pch = 20, col = rgb(1,0,0, 0.05), cex = 0.1)
              for(iii in 1 : length(opticalPoly))
              {
                     lines(opticalPoly[[iii]], col = "black", lty = "dashed", cex = 2)
              }
              
              
              dev.off()
       }
       
       
       
       
       return(img)
       
}

